create table  ORDER(
    ORDER_CODE INT PRIMARY key,
    M_ID INT NOT NULL,
    MENU_CODE INT NOT NULL,
    FINAL_AMT DECIMAL(15,0) NOT NULL,
    PAY_DATE DATE NOT NULL,
    PAY_TYPE VARCHER(10),
    ORDER_STATUS VARCHER(10),

    CONSTRAINT FK_ORDER_MEMBER
        FOREIGN KEY (M_ID)
        REFERENCES MEMBER(M_ID),

    CONSTRAINT FK_ORDER_MENU
        FOREIGN KEY (MENU_CODE)
        REFERENCES MENU(MENU_CODE)
)